config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'

  resources :campaigns, except: [:new, :create] do
    member do
      get 'images/:trash', to: 'campaigns#serve_image', as: :serve_image
      patch :archive, to: "campaigns#archive"
      get :twitter_form, defaults: { form: "twitter" }, as: :twitter_form, to: "campaigns#show"
    end
    resources :spam_reports, only: [:create]
  end

  resources :campaign_spreaders do
    collection do
      post(
      'create_for_facebook_profile',
      to: 'campaign_spreaders#create_for_facebook_profile',
      as: :create_for_facebook_profile
      )

      post(
      'create_for_twitter_profile',
      to: 'campaign_spreaders#create_for_twitter_profile',
      as: :create_for_twitter_profile
      )
    end
  end

  get '/auth/facebook/callback', to: 'campaign_spreaders#create_for_facebook_profile_callback'
  get '/auth/twitter/callback', to: 'campaign_spreaders#create_for_twitter_profile_callback'
  get '/auth/failure', to: 'campaign_spreaders#failure'

  get '/about', to: "pages#about", as: :about

  get ENV['CAS_SERVER_URL'] => 'campaigns#index', as: :login if Rails.env.test?
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :campaign_spreaders
  has_many :spam_reports
  has_many :facebook_profiles, through: :campaign_spreaders, source: :timeline, source_type: "FacebookProfile"
  has_many :twitter_profiles, through: :campaign_spreaders, source: :timeline, source_type: "TwitterProfile"
  belongs_to :organization
  belongs_to :user
  belongs_to :category
  belongs_to :mobilization, primary_key: :hashtag, foreign_key: :hashtag
  mount_uploader :image, ImageUploader
  mount_uploader :meta_image, ImageUploader
  mount_uploader :facebook_image, ImageUploader

  validates :ends_at, :share_link, :goal, :organization_id, :user_id, :category_id, :title, :description, :tweet, :new_campaign_spreader_mail, :facebook_title, :facebook_message, :short_description, presence: true
  validates :image, :facebook_image, presence: true, on: :create
  validate :ends_at_cannot_be_in_the_past
  validate :ends_at_cannot_be_in_more_than_50_days

  after_create { CampaignWorker.perform_async(self.id) }
  after_create { self.delay.create_mailchimp_segment }
  after_update { self.delay.update_mailchimp_segment }

  scope :shared,             -> { where("shared_at IS NOT NULL") }
  scope :unshared,           -> { where("shared_at IS NULL") }
  scope :unarchived,         -> { where("archived_at IS NULL") }
  scope :expiring,           -> { where("ends_at <= ? AND ends_at >= ?", Time.zone.now + 3.days, Time.zone.now) }
  scope :upcoming,           -> { where("? < ends_at", Time.zone.now) }
  scope :ended,              -> { where("? >= ends_at", Time.zone.now) }
  scope :succeeded,          -> { where("(
    SELECT count(*)
    FROM campaign_spreaders
    WHERE campaign_spreaders.campaign_id = campaigns.id) >= campaigns.goal")}
  scope :unsucceeded,        -> { ended.where("(
    SELECT count(*)
    FROM campaign_spreaders
    WHERE campaign_spreaders.campaign_id = campaigns.id) < campaigns.goal")}


  def share
    campaign_spreaders.each {|cs| cs.share}
    update_attribute :shared_at, Time.zone.now
  end

  def archive
    update_attribute :archived_at, Time.zone.now
  end

  def ends_at_cannot_be_in_the_past
    errors.add(:ends_at, I18n.t("errors.messages.cannot_be_in_the_past")) if
      ends_at.nil? || ends_at < Time.zone.now
  end

  def ends_at_cannot_be_in_more_than_50_days
    errors.add(:ends_at, I18n.t("errors.messages.cannot_be_in_more_than", 50.days)) if
      ends_at.nil? || ends_at > 50.days.from_now
  end

  def check_expired_tokens
    facebook_profiles.each { |fp| fp.check_expired_token }
  end

  def progress_of_goal
    campaign_spreaders.count.to_f/goal.to_f * 100
  end

  def progress_of_time
    (Time.zone.now - created_at)/(ends_at - created_at) * 100
  end

  def reach
    facebook_profiles.sum(:friends_count) +
      facebook_profiles.sum(:subscribers_count) +
      twitter_profiles.sum(:followers_count)
  end

  def archived?
    !self.archived_at.nil?
  end

  def succeeded?
    campaign_spreaders.count >= goal && ended?
  end

  def unsucceeded?
    campaign_spreaders.count < goal && ended?
  end

  def ended?
    ends_at < Time.zone.now
  end

  def create_mailchimp_segment
    begin
      segments = Gibbon::API.lists.segments(id: ENV["MAILCHIMP_LIST_ID"])
      segment = segments["static"].select{|s| s["name"] == mailchimp_segment_name}.first || Gibbon::API.lists.segment_add(
        id: ENV["MAILCHIMP_LIST_ID"],
        opts: { type: "static", name: mailchimp_segment_name }
      )
      self.update_attribute :mailchimp_segment_uid, segment["id"]
    rescue Exception => e
      puts e
      Rails.logger.error e
      Appsignal.add_exception e
    end
  end

  def update_mailchimp_segment
    begin
      Gibbon::API.lists.segment_update(
        id: ENV["MAILCHIMP_LIST_ID"],
        seg_id: self.mailchimp_segment_uid,
        opts: { name: mailchimp_segment_name }
      )
    rescue Exception => e
      Rails.logger.error e
      Appsignal.add_exception e
    end
  end

  def mailchimp_segment_name
    "CMP - #{self.id.to_s.rjust(4, "0")} - #{self.title}".byteslice(0..99)
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  load_and_authorize_resource except: [:serve_image]
  respond_to :html, :json

  def index
    @campaigns = Campaign
      .unarchived
      .upcoming
      .order(:ends_at)
      .page(params[:page])
      .per(9)
    
    @shared_campaigns = Campaign
      .unarchived
      .shared
      .order("random()")
      .limit(6)
  end

  def show
    @campaign = Campaign.find(params[:id])
    @last_spreaders = @campaign.campaign_spreaders.order(created_at: :desc).limit(5)
    @campaign_spreader = CampaignSpreader.new(campaign: @campaign)
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user

    if @campaign.save
      respond_with @campaign, notice: 'Campanha criada!'
    else
      render :new
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update(campaign_params)
      respond_with @campaign, notice: 'Campanha atualizada!'
    else
      render :edit
    end
  end

  def archive
    @campaign = Campaign.find(params[:id])
    @campaign.archive
    respond_with @campaign
  end

  def serve_image
    @campaign = Campaign.find(params[:id])
    send_data(
      @campaign.facebook_image.file.read,
      type: MIME::Types.type_for(@campaign.facebook_image.path).first.content_type,
      disposition: 'inline'
    )
  end

  def campaign_params
    params.fetch(:campaign, {}).permit(:title, :description, :image, :ends_at, :goal, :organization_id, :user_id, :category_id, :share_link, :tweet, :new_campaign_spreader_mail, :hashtag, :facebook_title, :facebook_message, :facebook_image, :meta_title, :meta_message, :meta_image, :short_description)
  end
end

app/views/campaigns/_campaign.html.slim
.campaign id="campaign-#{campaign.id}"
  .ends-at class="#{campaign.shared_at.present? ? 'shared' : ''}"
    .icon-clock2
      - if campaign.shared_at.present?
        span Disparado há #{distance_of_time_in_words_to_now campaign.ends_at}
      - else
        span Faltam #{distance_of_time_in_words_to_now campaign.ends_at}
  = link_to image_tag(campaign.image.thumb), campaign
  .box
    .title-wraper
      = link_to campaign do
        h4 title=campaign.title = truncate(campaign.title, length: 50)
      .organization= campaign.organization.city
    .user Por #{link_to campaign.user.name, user_path(campaign.user)}
    .category Em #{campaign.category.name}
    .progress.round.secondary
      span.meter style="width: #{number_to_percentage([campaign.progress_of_goal, 100].min, precision: 0)}"
      span.percentage class="#{campaign.progress_of_goal >= 100 ? "succeeded" : ""}"
        = number_to_percentage(campaign.progress_of_goal, precision: 0)
    .goal
      span= campaign.campaign_spreaders.count
      |  de #{campaign.goal} perfis emprestados

app/views/campaigns/_form.html.slim
= form_for @campaign, data: { abide: true } do |f|

  .row
    .form-title
      h4 Prepare seu grito: decida o que você quer que as pessoas compartilhem no Facebook.
    .facebook-form
      .box
        .row
          .facebook-title-field
            = f.label(:facebook_title, "Título do post", class: :required)
            .facebook-title-text-field= f.text_field(:facebook_title, required: true, disabled: disabled, maxlength: 70)
            = f.label(:facebook_message, 'Mensagem do post', class: :required)
            .facebook-message-text-area= f.text_area(:facebook_message, rows: 2, required: true, disabled: disabled, maxlength: 90)
          .share-link-field
            = f.label :share_link, 'Link a ser compartilhado', class: :required
            = f.url_field :share_link, required: true, value: (@campaign.share_link.present? ? @campaign.share_link : "http://"), disabled: disabled
          .facebook-image-field
            = f.label(:facebook_image, 'Imagem do post', class: :required)
            = f.file_field(:facebook_image, required: !@campaign.facebook_image.thumb.present?, disabled: disabled)
    .facebook-preview
      p
        strong Preview:
        |  como seu post será publicado nos perfis conectados a sua campanha.
      .facebook-preview-box
        .row
          .preview-image= image_tag (@campaign.facebook_image.thumb.present? ? @campaign.facebook_image.thumb : '')
          .preview-text
            .share-title= @campaign.facebook_title || 'Título do post'
            .share-description= @campaign.facebook_message || 'Mensagem do post'
            .share-link= link_to (@campaign.share_link || 'www.linkdopost.com'), "#"

  .row
    .form-title
      h4 Prepare seu grito: decida o que você quer que as pessoas compartilhem no Twitter.

    .twitter-form
      .box
        .row
          .tweet-field
            = f.label :tweet, class: :required do
              | Mensagem a ser tuítada
              span.has-tip data={tooltip: true} aria-haspopup=true title='Máximo de 140 caracteres e deve incluir o link que você quer dar visibilidade.'  ?
            .tweet-textarea= f.text_area :tweet, required: true, maxlength: 140, rows: 3, disabled: disabled

  .row
    .form-title
      h4 Programe o disparo do seu Compartilhaço:

    .share-form
      .box
        .row
          .ends-at-field
            = f.label :ends_at, class: :required do
              | Data de encerramento
              span.has-tip data={tooltip: true} aria-haspopup=true title='Se você atingir a meta até essa data seu Compartlihaço será disparado.'  ?
            = f.text_field :ends_at, required: true, data:{datetimepicker: true}, value: @campaign.ends_at.present? ? @campaign.ends_at.strftime("%Y/%m/%d %H:%M") : nil, disabled: disabled
          .goal-field
            = f.label(:goal, class: :required) do
              | Meta de apoio
              span.has-tip data={tooltip: true} aria-haspopup=true title='Quantidade mínima de perfis emprestados para que seu Compartilhaço seja disparado. Sugerimos um número entre 100 e 500 apoiadores para que sua campanha tenha relevância.'  ?
            .row.collapse
              .small-5.columns= f.number_field :goal, required: true, disabled: disabled
              .small-7.columns
                span.postfix perfis emprestados

  .row
    .form-title
      h4 Convença as pessoas a participar: informações sobre sua causa ou mobilização.

    .campaign-form
      .box
        .row
          .title-field
            = f.label :title, class: :required do
              | Título da sua página no Compartilhaço
              span.has-tip data={tooltip: true} aria-haspopup=true title="Um título curto e direto é sempre melhor!"  ?
            = f.text_field(:title, required: true)
          - if can?(:set_hashtag, Campaign)
            .hashtag-field
              = f.label :hashtag, "Tema"
              = f.collection_select(:hashtag, Mobilization.order(:title).all, :hashtag, :title, include_blank: "Escolha um tema")
          .organization-id-field
            = f.label :organization_id, "Cidade", class: :required
            = f.collection_select(:organization_id, Organization.order(:city).all, :id, :city, {include_blank: "Escolha uma cidade"}, required: true)
          .category-id-field
            = f.label :category_id, class: :required do
              | Categoria
              span.has-tip data={tooltip: true} aria-haspopup=true title="Ajude as pessoas a encontrarem sua campanha."  ?
            = f.collection_select(:category_id, Category.order(:name).all, :id, :name, {include_blank: "Escolha uma categoria"}, required: true)
          .image-field
            = f.label :image, 'Imagem (900x400)', class: :required
            = f.file_field(:image, required: !@campaign.image.thumb.present?)
            .preview-image= image_tag (@campaign.image.thumb.present? ? @campaign.image.thumb : '')
          .short-description-field
            = f.label :short_description, class: :required do
              | Resumo sobre o seu Compartilhaço
              span.has-tip data={tooltip: true} aria-haspopup=true title='Convença as pessoas a entenderem a importância de emprestarem seus perfis para a sua campanha em no máximo 160 caracteres.'  ?
            .short-description-text-area= f.text_area :short_description, required: true, rows: 2, maxlength: 160
          .description-field
            = f.label :description, class: :required do
              | História por trás do seu Compartilhaço
              span.has-tip data={tooltip: true} aria-haspopup=true title='Descreva em alguns parágrafos o problema, causa ou mobilização que você quer dar voz. Argumente com dados concretos e mostre a mudança que sua campanha pode causar no mundo.'  ?
            = f.text_area :description, required: true, rows: 3
  .row
    .form-title
      h4 Ao compartilhar a página deste Compartilhaço:

    .meta-form
      .box
        .row
          .meta-title-field
            = f.label :meta_title, 'Título do compartilhamento'
            = f.text_field :meta_title
          .meta-message-field
            = f.label :meta_message, 'Mensagem do compartilhamento'
            = f.text_area :meta_message
          .meta-image-field
            = f.label :meta_image, 'Imagem do compartilhamento'
            = f.file_field :meta_image
            .preview-image= image_tag (@campaign.meta_image.thumb.present? ? @campaign.meta_image.thumb : '')

  .row
    .form-title
      h4 Agradeça o gogó amigo:

    .email-form
      .box
        .row
          .new-campaign-spreader-mail-field
            = f.label :new_campaign_spreader_mail, class: :required do
              | Email para Apoiadores
              span.has-tip data={tooltip: true} aria-haspopup=true title='Agradecer é de muito bom tom. Deixar o link da sua campanha e pedir para as pessoa compartilharem em suas redes é estratégico! Fica aqui uma colinha! ;)'  ?
            = f.text_area(:new_campaign_spreader_mail, required: true, rows: 11, value: (@campaign.new_campaign_spreader_mail.present? ? @campaign.new_campaign_spreader_mail : "Obrigado por apostar na força da ação coletiva em rede e emprestar seu perfil para o meu Compartilhaço.\n\nCom muitas vozes nossas mensagens podem chegar ainda mais longe. Mas juntá-las não é tão simples assim.\n\nVocê pode continuar ajudando! Divulgue esse Compartilhaço nas suas redes para que essa causa consiga mais apoiadores e impacte milhares de pessoas.\n\nGrande abraço e até breve!\n#{current_user.name}"))
          .submit-field
            = f.submit 'Salvar Compartilhaço', id: 'campaign-submit-button', class: [:button, :radius, :large]

app/views/campaigns/edit.html.slim
.row
  .header
    h2 Edite seu compartilhaço
    h4.subheader Este aplicativo da Rede Nossas Cidades é livre e aceita todos os tipos de mobilização e causas. #{ link_to 'Clique aqui', '#policy', "data-reveal-id" => "policy", "data-reveal" => true } para saber o que não pode e o que é muito recomendado.
    h4.alert Você não pode editar um compartilhaço que já possui compartilhadores

= render 'form', disabled: @campaign.campaign_spreaders.any?
= render 'shared/policy'

app/views/campaigns/index.html.slim
ul.about-orbit data={orbit: true, options: "slide_number:false; resume_on_mouseout:true; navigation_arrows: false;"}
  li
    .row
      .illustration= image_tag "about-orbit/image-1.png"
      .content
        h2 Sua voz faz diferença.
        p Conecte seu Facebook e Twitter com o Compartilhaço pra dar visibilidade a uma mobilização ou causa de interesse público.
  li
    .row
      .illustration= image_tag "about-orbit/image-2.png"
      .content
        h2 Você não está falando sozinho.
        p Junte-se a mais e mais pessoas emprestando seu perfil até a meta para disparo do Compartilhaço ser atingida.
  li
    .row
      .illustration= image_tag "about-orbit/image-3.png"
      .content
        h2 Muitas vozes, uma mensagem.
        p Veja o mesmo post, ao mesmo tempo, aparecer em todos os perfis de Facebook e Twitter conectados.
  li
    .row
      .illustration= image_tag "about-orbit/image-4.png"
      .content
        h2 Juntos nossa voz chega mais longe!
        p Surpreenda-se com milhares de pessoas impactadas pela ação coletiva na rede.

.new-campaign
  .row
    .wrapper
      h3 Quer dar voz a esse coro?
      p= link_to "Crie um Compartilhaço", "#", class: [:button, :radius, :large, :secondary, :disabled]
      p
        small= link_to "Saiba mais", about_path

- if @shared_campaigns.any?
  .row
    .campaigns-list-title
      h3 Compartilhaços vitoriosos

  #shared-campaigns-list.campaigns-list
    .row
      = render @shared_campaigns

.row
  .campaigns-list-title
    h3 Ajude um compartilhaço em sua reta final!

#campaigns-list.campaigns-list
  .row
    - if @campaigns.empty?
      .empty Nenhum compartilhaço encontrado
    - else
      = render @campaigns

= paginate @campaigns

app/views/campaigns/new.html.slim
.row
  .header
    h2 Crie seu compartilhaço
    h4.subheader Se você quer aumentar o alcance de uma mobilização ou causa social você veio ao lugar certo. Aqui você encontra o apoio de muitas vozes pra que sua mensagem chegue mais longe. Crie agora o seu Compartilhaço e seja o protagonista da mudança que você quer pro mundo!
    h4.subheader Este aplicativo da Rede Nossas Cidades é livre e aceita todos os tipos de mobilização e causas. Mas é sempre bom lembrar, tem coisa que a nossa rede adora, e outras que preferimos passar longe. #{ link_to 'Clique aqui', '#policy', "data-reveal-id" => "policy", "data-reveal" => true } para saber o que não pode e o que é muito recomendado.

= render 'form', disabled: false
= render 'shared/policy'

app/views/campaigns/show.html.slim
- set_meta_tags title: @campaign.title
- set_meta_tags description: @campaign.short_description
- set_meta_tags og: { title: @campaign.meta_title || @campaign.title }
- set_meta_tags og: { description: @campaign.meta_message || @campaign.short_description }
- set_meta_tags og: { image: @campaign.meta_image.url || @campaign.image.url }
- set_meta_tags og: { url: campaign_url(@campaign) }
- set_meta_tags twitter: { card: "summary" }
- set_meta_tags twitter: { title: @campaign.meta_title || @campaign.title }
- set_meta_tags twitter: { description: @campaign.meta_message || @campaign.short_description }
- set_meta_tags twitter: { image: @campaign.meta_image.thumb.url || @campaign.image.thumb.url }
- set_meta_tags twitter: { url: campaign_url(@campaign) }
- set_meta_tags twitter: { site: "@meu_rio" }

.campaign-highlight class=campaign_highlight_class(@campaign)
  .row
    .campaign-data
      .category= @campaign.category.name
      h2= @campaign.title
      .short-description= @campaign.short_description

      .total-spreaders
        .left.icon-users
          span Perfis emprestados
        .right
          span.total-spreaders-count= @campaign.campaign_spreaders.count
          | /
          span.total-spreaders-goal= @campaign.goal
        .clear
        .progress.round.secondary
          span.meter style="width: #{number_to_percentage([@campaign.progress_of_goal, 100].min, precision: 0)}"

      .ends-at
        .left.icon-clock2
          span Tempo para encerramento
        .right
          span.ends-at-distance= @campaign.ends_at.future? ? distance_of_time_in_words(Time.zone.now, @campaign.ends_at) : "Encerrado"
        .clear
        .progress.round.alert
          span.meter style="width: #{number_to_percentage([@campaign.progress_of_time, 100].min, precision: 0)}"
        span Encerra: #{l(@campaign.ends_at, format: :short)}

      .reach
        span.reach-count
          = image_tag "reach.png"
          = number_with_delimiter @campaign.reach
        span.reach-label  pessoas serão alcançadas

    .campaign-forms
      .campaign-menu
        - if can?(:edit, Campaign)
          = link_to "Editar", edit_campaign_path(@campaign), id: :edit_campaign_button
          span.divider
        - if can?(:archive, @campaign)
          = link_to "Arquivar", archive_campaign_path(@campaign), method: :patch, id: :archive_campaign_button, disabled: @campaign.archived?, data: { confirm: "Deseja arquivar este compartilhaço?" }
          span.divider
        - if can?(:create, SpamReport)
          = link_to "Denunciar", campaign_spam_reports_path(@campaign), method: :post, id: "spam-report-button", data: { confirm: "Deseja denunciar este compartilhaço?" }

      - if @campaign.archived?
        = image_tag("archived-campaign-icon.png")
        h2 Esse Compartilhaço foi arquivado #{distance_of_time_in_words_to_now @campaign.archived_at} atrás.
      - elsif @campaign.succeeded?
        = image_tag("succeeded-campaign-icon.png")
        h2 Uhul, esse Compartilhaço atingiu sua meta e foi disparado há #{distance_of_time_in_words_to_now @campaign.ends_at}!
      - elsif @campaign.unsucceeded?
        = image_tag("unsucceeded-campaign-icon.png")
        h2 Que pena, esse compartilhaço não atingiu sua meta de disparo!
      - else
        .form-buttons
          = link_to "Facebook", campaign_path(@campaign), class: ["facebook-form-button", facebook_form_button_class], id: "facebook-form-button"
          = link_to "Twitter", twitter_form_campaign_path(@campaign), class: ["twitter-form-button", twitter_form_button_class], id: "twitter-form-button"
        - if facebook_form?
          = form_for @campaign_spreader, url: create_for_facebook_profile_campaign_spreaders_path, data: { abide: true }, html: { class: "facebook-profile-campaign-spreader" } do |form|
            = form.hidden_field(:campaign_id)
            .message-field= form.text_area :message, rows: 3, placeholder: "Escreva algo, se quiser, sobre a importância de dar visibilidade à esse Compartilhaço!"
            .facebook-preview-box
              .row
                .preview-image= image_tag @campaign.facebook_image.thumb
                .preview-text
                  .share-title= @campaign.facebook_title
                  .share-description= @campaign.facebook_message
                  .share-link= link_to @campaign.share_link, @campaign.share_link, target: :blank
            .row
              - if current_user.nil?
                = form.fields_for :timeline do |timeline_form|
                  = timeline_form.fields_for :user do |user_form|
                    .user-email-field
                      = user_form.email_field(:email, required: true, placeholder: "Insira seu e-mail")
                      small.error Email é obrigatório
              .submit-field class=('center' if current_user.present?) = form.submit "Emprestar Facebook", id: "facebook-profile-campaign-spreader-submit-button", class: [:button, :radius, :large]

        - elsif twitter_form?
          = form_for @campaign_spreader, url: create_for_twitter_profile_campaign_spreaders_path, data: { abide: true }, html: { class: "twitter-profile-campaign-spreader" } do |form|
            = form.hidden_field(:campaign_id)
            .message-field
              = form.text_area :message, required: true, maxlength: 140, rows: 3, value: @campaign.tweet
              small.error Você precisa escrever uma mensagem de até 140 caracteres
            .row
              - if current_user.nil?
                = form.fields_for :timeline do |timeline_form|
                  = timeline_form.fields_for :user do |user_form|
                    .user-email-field
                      = user_form.email_field(:email, required: true, placeholder: "Insira seu email")
                      small.error Email é obrigatório
              .submit-field class=('center' if current_user.present?) = form.submit "Emprestar Twitter", id: "twitter-profile-campaign-spreader-submit-button", class: [:button, :radius, :large]

        small.warn Se o Compartilhaço atingir a sua meta até a data de encerramento, essa mensagem será publicada automaticamente no seu perfil e de muitas outras pessoas. #{ link_to 'Saiba mais.', about_path }

.row
  .campaign-left-col
    = image_tag @campaign.image.wide
    = simple_format @campaign.description
    .campaign-comments
      h3 Comentários
      .fb-comments data-href=campaign_url(@campaign) data-width="100%" data-numposts="10"
  .campaign-right-col
    .campaign-user
      h3 Quem inicia o coro:
      .user
        = image_tag @campaign.user.avatar_url
        .user-name= @campaign.user.name
        .user-link= link_to("Ver perfil", user_path(@campaign.user))
    .last-spreaders
      h3 Quem empresta sua voz #{content_tag :span, "(#{@campaign.campaign_spreaders.try(:count)})"}:
      = render @last_spreaders

.reveal-modal.share.medium data={reveal: true}
  = image_tag "share-campaign.png"
  h3 Sucesso!!! Agora espalhe por aí!
  p Obrigado por emprestar sua voz a esse Compartilhaço. Agora precisamos ampliar esse coro. Mostre pra toda sua rede que a ajuda de cada um deles pode fazer essa causa impactar milhares de pessoas!
  .share-buttons
    = link_to "Compartilhe no Facebook", "#", class: ['share-on-facebook-button', :button, :radius], data: { href: "https://www.facebook.com/sharer/sharer.php?u=#{URI::encode(campaign_url(@campaign))}" }
    = link_to "Compartilhe no Twitter", "#", class: ['share-on-twitter-button', :button, :radius], data: { href: "https://twitter.com/share?url=#{campaign_url(@campaign)}&text=#{@campaign.title}" }
  a.close-reveal-modal &#215;